### ISSUE TITLE
We need a way to track statuses and add story/scene tags 

### ISSUE THREAD

**Issue by olterman** [aMediocreDad/litm#33] opened 2024-03-08 08:57 UTC
It would be amazing if Limits added to challenges could be tracked for example on the icon so that one could count it down like HP. And there shopuld be a way to add story and scenbe tags that players can use

**Comment by aMediocreDad** [comment] 2024-03-08 09:49
Duplicate of: https://github.com/aMediocreDad/litm/issues/17

**Closed** 2024-03-08 09:49 UTC
