### ISSUE TITLE
Import adventure loses token's Image path

### ISSUE THREAD

**Issue by Sigrlin** [aMediocreDad/litm#76] opened 2024-09-25 17:24 UTC
After the importing of the adventure all tokens that I made lose Image path
![tammi-lu](https://github.com/user-attachments/assets/c4da46cb-2a4b-47a5-a224-80001eb93420)

Build 315, Version 11
Legend in the Mist ver 20

**Comment by aMediocreDad** [comment] 2024-09-25 20:48
Hi! This system no longer supports v11 of Foundry. I would recommend moving to v12.

I will check one hook that deals with creation of actors and assigns token images if they do not have a predefined image however.

**Comment by aMediocreDad** [comment] 2024-10-12 16:46
Afraid I cannot reproduce this. I did this:

1. Create a new world.
2. Create a character, assign it a portrait and prototype token image.
3. Import the Tinderbox Adventure.
4. Verify that the Token Image did not change.

**Closed by aMediocreDad** 2024-10-12 16:46 UTC
